# The ID of the dataset you created above.
dataset: hipaa-compliance-2

text_completion:
  # How the fields of the JSON dataset should be formatted into the input text.
  input_template: "### GIVEN THE CONTEXT: {context}  ### INSTRUCTION: {instruction}  ### RESPONSE IS: "
  
  # How the fields of the JSON dataset should be formatted into the output text.
  output_template: "ANSWER: {response}"

# The Hugging Face model name of the base model.
base_model: mistralai/Mistral-7B-v0.1